
"use strict";
const $=id=>document.getElementById(id);
let curFilter="all",curSearch="",editingId=null,currentItem=null,coverData="",isOwnerSession=false;
let audioEl=null,isPlaying=false,audioCtx=null,analyser=null,rafId=null,songObjectUrl=null,lastAct=Date.now();
let mx=0,my=0,cx=0,cy=0,gx=0,gy=0,threePts=null,threeRen=null,threeAnim=null;
const esc=s=>String(s||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function toast(m){const t=$("toast");t.textContent=m;t.style.display="block";requestAnimationFrame(()=>t.classList.add("show"));clearTimeout(t._h);t._h=setTimeout(()=>{t.classList.remove("show");setTimeout(()=>t.style.display="none",300)},1800)}
function uid(){return "p"+Date.now().toString(36)+Math.floor(Math.random()*999)}
function curUser(){return localStorage.getItem("darkzhub-user")||"guest"}
function getProjects(){try{const v=JSON.parse(localStorage.getItem("darkzhub-projects-v1")||"[]");return Array.isArray(v)?v:[]}catch{return[]}}
function saveProjects(p){try{localStorage.setItem("darkzhub-projects-v1",JSON.stringify(p))}catch{toast("Storage full — export a backup")}}
function getAbout(){try{return JSON.parse(localStorage.getItem("darkzhub-about-v1")||"null")}catch{return null}}
function saveAboutStore(a){try{localStorage.setItem("darkzhub-about-v1",JSON.stringify(a))}catch{toast("Storage full — export a backup")}}
function unlocked(){try{const v=JSON.parse(localStorage.getItem("darkzhub-unlocked")||"[]");return Array.isArray(v)?v:[]}catch{return[]}}
const THEMES=[{id:"midnight",n:"Midnight",c:"linear-gradient(135deg,#050507,#E50914)"},{id:"carbon",n:"Carbon Red",c:"linear-gradient(135deg,#000,#ff1a1a)"},{id:"navy",n:"Navy Ops",c:"linear-gradient(135deg,#040917,#2a7bff)"},{id:"toxic",n:"Toxic",c:"linear-gradient(135deg,#000,#00ff88)"},{id:"onyx",n:"Onyx Purple",c:"linear-gradient(135deg,#000,#8b00ff)"},{id:"ice",n:"Ice Soldier",c:"linear-gradient(135deg,#000,#00d4ff)"},{id:"ember",n:"Ember",c:"linear-gradient(135deg,#000,#ff5a00)"},{id:"stealth",n:"Stealth Grey",c:"linear-gradient(135deg,#000,#9aa0aa)"},{id:"gold",n:"Gold King",c:"linear-gradient(135deg,#000,#d4af37)"},{id:"matrix",n:"Matrix",c:"linear-gradient(135deg,#000,#00ff00)"}];
const BGS=[{id:"orbs",n:"Orbs",d:"soft glow orbs",p:"radial-gradient(circle at 30% 30%,rgba(255,255,255,.9),transparent 60%),radial-gradient(circle at 70% 60%,rgba(255,255,255,.25),transparent 70%),#0a0a12"},{id:"aurora",n:"Aurora",d:"wide color wash",p:"linear-gradient(135deg,#0a0a18,#10202a 40%,#0a1420 70%,#0a0a18),radial-gradient(ellipse 80% 50% at 50% 0%,rgba(0,212,255,.25),transparent 70%)"},{id:"stars",n:"Stars",d:"tiny sharp stars",p:"radial-gradient(ellipse at center,#050508 0%,#000 100%)"},{id:"emberbg",n:"Ember",d:"warm rising dust",p:"radial-gradient(ellipse at 50% 100%,rgba(255,90,0,.2),transparent 60%),#070402"},{id:"nebula",n:"Nebula",d:"purple deep cloud",p:"radial-gradient(circle at 20% 20%,rgba(139,0,255,.3),transparent 50%),radial-gradient(circle at 80% 80%,rgba(0,212,255,.2),transparent 50%),#050510"},{id:"grid",n:"Grid",d:"clean perspective grid",p:"linear-gradient(#0a0a12,#0a0a12)"}];
function getTheme(){return localStorage.getItem("darkzhub-theme")||"midnight"}
function setTheme(t){if(!THEMES.some(x=>x.id===t))t="midnight";localStorage.setItem("darkzhub-theme",t);document.body.dataset.theme=t;$("themeKicker").textContent=(THEMES.find(x=>x.id===t)?.n||t).toUpperCase()+" — "+(BGS.find(x=>x.id===getBg())?.n||"").toUpperCase();renderThemes()}
function renderThemes(){if(!$("themeGrid"))return;const cur=getTheme();$("themeGrid").innerHTML=THEMES.map(t=>`<div class="themeBtn ${t.id===cur?"on":""}" onclick="setTheme('${t.id}')"><div class="themeDot" style="background:${t.c}"></div>${esc(t.n)}</div>`).join("")}
function getBg(){const b=localStorage.getItem("darkzhub-bg")||"orbs";return BGS.some(x=>x.id===b)?b:"orbs"}
function setBg(b){if(!BGS.some(x=>x.id===b))b="orbs";localStorage.setItem("darkzhub-bg",b);document.body.dataset.bg=b;$("themeKicker").textContent=(THEMES.find(x=>x.id===getTheme())?.n||"").toUpperCase()+" — "+(BGS.find(x=>x.id===b)?.n||b).toUpperCase();renderBgs();initThree()}
function renderBgs(){const cur=getBg();if(!$("bgGrid"))return;$("bgGrid").innerHTML=BGS.map(b=>`<div class="bgBtn ${b.id===cur?"on":""}" onclick="setBg('${b.id}')"><div class="bgPrev" style="background:${b.p}"></div><b>${esc(b.n)}</b><div style="font-size:11px;color:var(--muted)">${esc(b.d)}</div></div>`).join("")}
function toggleSmooth(){const off=document.body.classList.toggle("no-motion");localStorage.setItem("darkzhub-smooth",off?"0":"1");$("smoothBtn").textContent="Smooth: "+(off?"OFF":"ON")}
function toggleParticles(){const cur=localStorage.getItem("darkzhub-particles")!=="0";localStorage.setItem("darkzhub-particles",cur?"0":"1");$("particleBtn").textContent="Particles: "+(cur?"OFF":"ON");initThree()}
function stopThree(){if(threeAnim)cancelAnimationFrame(threeAnim);threeAnim=null;if(threeRen){threeRen.dispose();threeRen=null}threePts=null;const cv=$("bg3d");if(cv){const ctx=cv.getContext("webgl");if(ctx)ctx.clearColor(0,0,0,0)}}
function openSettings(){renderThemes();renderBgs();$("settingsModal").style.display="flex"}
function closeSettings(){$("settingsModal").style.display="none"}
async function hashPw(s){try{const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode("darkz::"+s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}catch{let h=0;for(let i=0;i<s.length;i++)h=(h*31+s.charCodeAt(i))>>>0;return "f"+h.toString(16)}}
function hasAuth(){return !!localStorage.getItem("darkzhub-auth-hash")}
function checkSession(){const t=sessionStorage.getItem("hubAuth");if(!t)return false;if(Date.now()-Number(t)>20*60*1000){sessionStorage.removeItem("hubAuth");return false}return true}
function renderLock(){const has=hasAuth();$("setupBox").style.display=has?"none":"block";$("loginBox").style.display=has?"block":"none";if(isOwnerSession&&has){$("lockBox").style.display="none";$("dashMain").style.display="grid"}else if(!has){$("lockBox").style.display="block";$("dashMain").style.display="none"}else{$("lockBox").style.display=isOwnerSession?"none":"block";$("dashMain").style.display=isOwnerSession?"grid":"none"}}
async function setupFirstPass(){const a=$("newPass1").value,b=$("newPass2").value;if(a.length<4){toast("Use 4+ characters");return}if(a!==b){toast("Passwords don't match");return}localStorage.setItem("darkzhub-auth-hash",await hashPw(a));sessionStorage.setItem("hubAuth",Date.now()+"");isOwnerSession=true;$("newPass1").value="";$("newPass2").value="";renderLock();renderDash();toast("Password set")}
async function loginDash(){const v=$("pinIn").value;if(!v)return;const h=await hashPw(v);if(h===localStorage.getItem("darkzhub-auth-hash")){isOwnerSession=true;sessionStorage.setItem("hubAuth",Date.now()+"");lastAct=Date.now();$("pinIn").value="";renderLock();renderDash();syncDashInputs();toast("Unlocked")}else toast("Wrong password")}
function lockDash(){isOwnerSession=false;sessionStorage.removeItem("hubAuth");renderLock();renderDash();toast("Locked")}
async function changePassword(){const o=$("oldPass").value,n=$("newPassChange").value;if(n.length<4){toast("New password needs 4+ characters");return}if((await hashPw(o))!==localStorage.getItem("darkzhub-auth-hash")){toast("Current password is wrong");return}localStorage.setItem("darkzhub-auth-hash",await hashPw(n));$("oldPass").value="";$("newPassChange").value="";toast("Password changed")}
function resetHub(){if(!confirm("Reset hub? 🗑️"))return;localStorage.removeItem("darkzhub-seeded");location.reload()}
function idbOpen(){return new Promise((res,rej)=>{const r=indexedDB.open("darkzhub-db",1);r.onupgradeneeded=()=>r.result.createObjectStore("files");r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function idbSet(k,v){const db=await idbOpen();return new Promise((res,rej)=>{const tx=db.transaction("files","readwrite");tx.objectStore("files").put(v,k);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
async function idbGet(k){const db=await idbOpen();return new Promise((res,rej)=>{const q=db.transaction("files","readonly").objectStore("files").get(k);q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
async function idbDel(k){const db=await idbOpen();return new Promise(res=>{const tx=db.transaction("files","readwrite");tx.objectStore("files").delete(k);tx.oncomplete=res;tx.onerror=res})}
function seed(){if(getProjects().length||localStorage.getItem("darkzhub-seeded"))return;saveProjects([{id:uid(),title:"Unseen Liminality",kind:"game",desc:"Backrooms horror — Rojo + Luau",cover:"https://picsum.photos/seed/liminal-hub/800/450",tags:["roblox","horror"],visibility:"public",allowed:[],code:"",link:"",files:[]},{id:uid(),title:"NOVAFLIX",kind:"site",desc:"Netflix-style catalog experiment",cover:"https://picsum.photos/seed/novaflix-hub/800/450",tags:["web"],visibility:"public",allowed:[],code:"",link:"",files:[]}]);
saveAboutStore({name:"Darkz",role:"Creator",tag:"",bio:"",avatar:"https://picsum.photos/seed/darkz-avatar/300/300",songTitle:"",songUrl:"",timeline:[]});localStorage.setItem("darkzhub-seeded","1")}
function canSee(p){if(p.visibility!=="private")return true;if(isOwnerSession)return true;if((p.allowed||[]).includes(curUser()))return true;if(unlocked().includes(p.id))return true;return false}
function goHome(){$("homeView").style.display="block";$("dashView").style.display="none";renderAll()}
function scrollToId(id){document.getElementById(id)?.scrollIntoView({behavior:"smooth"})}
function switchUser(){const n=prompt("Username? 👤",curUser());if(!n)return;localStorage.setItem("darkzhub-user",n.trim().slice(0,16));$("userBtn").textContent="@"+esc(n.trim().slice(0,12));renderProjects()}
function setFilter(f,el){curFilter=f;document.querySelectorAll("#filters .fPill").forEach(x=>x.classList.remove("on"));el.classList.add("on");renderProjects()}
function onSearch(v){curSearch=v.toLowerCase();renderProjects()}
function fmt(s){if(!isFinite(s))return "0:00";s=Math.floor(s);return Math.floor(s/60)+":"+String(s%60).padStart(2,"0")}
function buildEq(){const e=$("eq");if(e.children.length)return;let h="";for(let i=0;i<28;i++)h+="<span></span>";e.innerHTML=h}
function initAudio(){audioEl=$("audioEl");buildEq();audioEl.addEventListener("timeupdate",()=>{if(!audioEl.duration)return;$("progBar").style.width=(audioEl.currentTime/audioEl.duration*100)+"%";$("songTime").textContent=fmt(audioEl.currentTime)+" / "+fmt(audioEl.duration)});audioEl.addEventListener("ended",()=>{isPlaying=false;$("musicPlayer").classList.remove("playing");$("playBtn").textContent="▶"})}
function setupVisualizer(){try{if(!audioCtx){audioCtx=new (window.AudioContext||window.webkitAudioContext)();analyser=audioCtx.createAnalyser();analyser.fftSize=64;const src=audioCtx.createMediaElementSource(audioEl);src.connect(analyser);analyser.connect(audioCtx.destination)}audioCtx.resume()}catch{analyser=null}}
function vizLoop(){if(!isPlaying)return;if(analyser){const d=new Uint8Array(analyser.frequencyBinCount);analyser.getByteFrequencyData(d);document.querySelectorAll("#eq span").forEach((b,i)=>{const v=d[i%32]/255;b.style.animation="none";b.style.height=(12+v*88)+"%"})}rafId=requestAnimationFrame(vizLoop)}
async function togglePlay(){if(!audioEl.src){toast("Add a track in the studio first");return}if(isPlaying){audioEl.pause();isPlaying=false;$("musicPlayer").classList.remove("playing");$("playBtn").textContent="▶";cancelAnimationFrame(rafId)}else{try{setupVisualizer()}catch{}await audioEl.play();isPlaying=true;$("musicPlayer").classList.add("playing");$("playBtn").textContent="⏸";vizLoop()}}
function seekSong(e){if(!audioEl.duration)return;const r=$("progWrap").getBoundingClientRect();audioEl.currentTime=((e.clientX-r.left)/r.width)*audioEl.duration}
async function loadSong(){const a=getAbout()||{};$("songTitle").textContent=(a.songTitle||"No track yet")+" 🎵";if(a.songUrl){if(songObjectUrl)URL.revokeObjectURL(songObjectUrl);audioEl.src=a.songUrl;return}try{const blob=await idbGet("profile-song");if(blob){if(songObjectUrl)URL.revokeObjectURL(songObjectUrl);songObjectUrl=URL.createObjectURL(blob);audioEl.src=songObjectUrl}}catch{}}
async function handleSong(el){const f=el.files[0];if(!f)return;await idbSet("profile-song",f);const a=getAbout()||{};a.songTitle=$("aSongIn").value||f.name;a.songUrl="";saveAboutStore(a);if(songObjectUrl)URL.revokeObjectURL(songObjectUrl);songObjectUrl=URL.createObjectURL(f);audioEl.src=songObjectUrl;$("songTitle").textContent=a.songTitle+" 🎵";toast("Track saved")}
function previewSong(){const u=$("aSongUrlIn").value.trim();if(!u)return;audioEl.src=u;audioEl.play().then(()=>{isPlaying=true;$("musicPlayer").classList.add("playing");$("playBtn").textContent="⏸";vizLoop()}).catch(()=>toast("Can't play that URL"))}
async function removeSong(){await idbDel("profile-song");const a=getAbout()||{};a.songTitle="";a.songUrl="";saveAboutStore(a);audioEl.removeAttribute("src");audioEl.load();isPlaying=false;$("musicPlayer").classList.remove("playing");$("playBtn").textContent="▶";$("songTitle").textContent="No track yet 🎵";toast("Track removed")}
function renderAll(){seed();if(!audioEl)initAudio();const a=getAbout()||{name:"Darkz",tag:"",bio:"",avatar:"",timeline:[]};$("hName").textContent=(a.name||"Darkz");/* tagline folded into bio subhead */$("hBio").textContent=(a.bio||"A personal hub for games, sites and experiments.").slice(0,220);$("aName").textContent=a.name||"Darkz";$("avatar").src=a.avatar||"https://picsum.photos/seed/darkz-avatar/300/300";$("aboutBio").textContent=a.bio||"";$("timeline").innerHTML=(a.timeline||[]).map(t=>`<div class="tl-item">${esc(t)}</div>`).join("");$("userBtn").textContent="@"+curUser();loadSong();renderProjects()}
function syncDashInputs(){const a=getAbout()||{};$("aNameIn").value=a.name||"Darkz";$("aTagIn").value=a.tag||"";$("aBioIn").value=a.bio||"";$("aTimeIn").value=(a.timeline||[]).join("\n");$("aSongIn").value=a.songTitle||"";$("aSongUrlIn").value=a.songUrl||""}
function renderProjects(){let all=getProjects();$("stGames").textContent=all.filter(p=>p.kind==="game").length;$("stSites").textContent=all.filter(p=>p.kind==="site").length;$("stFiles").textContent=all.reduce((s,p)=>s+(p.files||[]).length,0);let list=all.filter(p=>{if(curFilter==="game"&&p.kind!=="game")return false;if(curFilter==="site"&&p.kind!=="site")return false;if(curFilter==="public"&&p.visibility==="private")return false;if(curFilter==="private"&&p.visibility!=="private")return false;if(curSearch&&!(p.title+p.desc+(p.tags||[]).join(" ")).toLowerCase().includes(curSearch))return false;return true});$("projCount").textContent=list.length+" SHIPPED";$("grid").innerHTML=list.length?list.map(p=>{const l=!canSee(p);return `<div class="pcard" onclick='openProject("${p.id}")'>${p.cover?`<img class="cover" src="${esc(p.cover)}" alt="" loading="lazy" onerror="this.remove()">`:""}<div class="body"><div class="tags"><span class="tag ${p.visibility==="private"?"priv":"pub"}">${p.visibility==="private"?"PRIVATE":"PUBLIC"}</span><span class="tag">${esc(p.kind).toUpperCase()}</span></div><h3>${esc(p.title)}</h3><p>${esc((p.desc||"").slice(0,110))}</p></div>${l?`<div class="plock"><b>Private — code to view</b><input id="code-${p.id}" placeholder="••••" onclick="event.stopPropagation()" onkeydown="if(event.key==='Enter'){event.stopPropagation();unlockPrivate('${p.id}')}" aria-label="Access code"><button class="btn ghost" onclick='event.stopPropagation();unlockPrivate("${p.id}")'>Unlock</button></div>`:""}</div>`}).join(""):'<div class="empty">Nothing here yet — open the studio and ship something.</div>'}
function openProject(id){const p=getProjects().find(x=>x.id===id);if(!p)return;if(!canSee(p)){toast("Private — code required");return}currentItem=p;$("modal").style.display="flex";document.body.style.overflow="hidden";if(p.cover){$("mHero").style.display="block";$("mHero").style.backgroundImage=`url("${String(p.cover||"").replace(/"/g,"")}")`}else{$("mHero").style.display="none"}$("mTitle").textContent=p.title;$("mBadges").innerHTML=`<span class="tag ${p.visibility==="private"?"priv":"pub"}">${p.visibility==="private"?"PRIVATE":"PUBLIC"}</span><span class="tag">${esc(p.kind).toUpperCase()}</span>`;$("mDesc").textContent=p.desc||"";$("mFiles").innerHTML=(p.files||[]).length?p.files.map(f=>f.type==="text"?`<div class="frow"><div><b>${esc(f.name)}</b><pre>${esc(f.text||"")}</pre></div></div>`:`<div class="frow"><img src="${esc(f.data||"")}" alt="" loading="lazy"><div><b>${esc(f.name)}</b></div></div>`).join(""):'<p style="color:var(--faint);font-size:13px">No files attached.</p>'}
function closeModal(){$("modal").style.display="none";document.body.style.overflow="auto"}
function playPrimary(){if(currentItem?.link){try{const u=new URL(currentItem.link);if(u.protocol==="http:"||u.protocol==="https:")window.open(u.href,"_blank","noopener");else toast("That link looks invalid")}catch{toast("That link looks invalid")}}else toast("No link attached")}
function editFromModal(){if(!isOwnerSession){toast("Unlock the studio to edit");closeModal();openDash();return}const id=currentItem?.id;closeModal();openDash();if(id)openEditor(id)}
function unlockPrivate(id){const p=getProjects().find(x=>x.id===id);const v=(document.getElementById("code-"+id)?.value||"").trim();if(p&&(v===p.code||(p.allowed||[]).includes(curUser()))){localStorage.setItem("darkzhub-unlocked",JSON.stringify([...new Set([...unlocked(),id])]));renderProjects();openProject(id)}else toast("Wrong code")}
function openDash(){$("homeView").style.display="none";$("dashView").style.display="block";if(checkSession())isOwnerSession=true;renderLock();if(isOwnerSession){renderDash();syncDashInputs()}window.scrollTo({top:0,behavior:"smooth"})}
function renderDash(){if(!isOwnerSession){renderLock();return}renderLock();const all=getProjects();$("dashList").innerHTML=all.length?all.map(p=>`<div class="ditem">${p.cover?`<img src="${esc(p.cover)}" alt="" loading="lazy" onerror="this.remove()">`:""}<div class="grow"><b>${esc(p.title)}</b><span>${esc(p.kind)} — ${p.visibility}</span></div><button class="btn ghost" onclick='openEditor("${p.id}")'>Edit</button><button class="btn ghost" onclick='delProject("${p.id}")'>Del</button></div>`).join(""):'<p style="color:var(--faint)">Nothing yet.</p>';renderFileBox()}
function renderFileBox(){const p=getProjects().find(x=>x.id===editingId);if(!p){$("fileHint").textContent="Save a project first.";$("fileBox").innerHTML="";return}$("fileHint").textContent="Files — "+p.title;$("fileBox").innerHTML=(p.files||[]).map((f,i)=>`<div class="ditem"><div class="grow"><b>${esc(f.name)}</b>${f.type==="text"?`<textarea onchange='editText(${i},this.value)'>${esc(f.text||"")}</textarea>`:`<img src="${esc(f.data||"")}" alt="" loading="lazy" style="max-width:120px;border-radius:8px;margin-top:6px">`}</div><button class="btn ghost" onclick="delFile(${i})">Del</button></div>`).join("")||'<p style="color:var(--faint)">No files.</p>'}
function togglePriv(){$("privBox").style.display=$("fVis").value==="private"?"block":"none"}
function handleCover(el){const f=el.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{coverData=r.result;$("coverPrev").src=coverData;$("coverPrev").style.display="block"};r.readAsDataURL(f)}
function handleAvatar(el){const f=el.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{const a=getAbout()||{};a.avatar=r.result;saveAboutStore(a);renderAll()};r.readAsDataURL(f)}
function openEditor(id){const p=getProjects().find(x=>x.id===id);editingId=id||null;if(!p){resetEditor();return}$("edTitle").textContent="✏️ Edit: "+p.title;$("fTitle").value=p.title;$("fKind").value=p.kind;$("fDesc").value=p.desc||"";$("fLink").value=p.link||"";$("fTags").value=(p.tags||[]).join(", ");$("fVis").value=p.visibility;$("fAllowed").value=(p.allowed||[]).join(", ");$("fCode").value=p.code||"";coverData=p.cover||"";if(coverData){$("coverPrev").src=coverData;$("coverPrev").style.display="block"}togglePriv();renderFileBox()}
function resetEditor(){editingId=null;$("edTitle").textContent="➕ New Project";["fTitle","fDesc","fLink","fTags","fAllowed","fCode"].forEach(id=>$(id).value="");coverData="";$("coverPrev").style.display="none";renderFileBox()}
function saveProject(){if(!isOwnerSession){toast("Unlock the studio first");return}const t=$("fTitle").value.trim();if(!t){toast("Give it a title first");return}let all=getProjects();const obj={id:editingId||uid(),title:t.slice(0,80),kind:["game","site","other"].includes($("fKind").value)?$("fKind").value:"other",desc:$("fDesc").value.slice(0,2000),link:$("fLink").value.trim().slice(0,500),tags:$("fTags").value.split(",").map(s=>s.trim()).filter(Boolean).slice(0,12),visibility:$("fVis").value==="private"?"private":"public",allowed:$("fAllowed").value.split(",").map(s=>s.trim()).filter(Boolean).slice(0,32),code:$("fCode").value.trim().slice(0,64),cover:coverData||`https://picsum.photos/seed/${encodeURIComponent(t)}/800/450`,files:(all.find(x=>x.id===editingId)?.files||[])};all=editingId?all.map(x=>x.id===editingId?obj:x):[obj,...all];editingId=obj.id;saveProjects(all);renderAll();renderDash();toast("Saved")}
function delProject(id){if(!confirm("Delete? 🗑️"))return;saveProjects(getProjects().filter(x=>x.id!==id));if(editingId===id)resetEditor();renderAll();renderDash()}
function addTextFile(){const p=getProjects().find(x=>x.id===editingId);if(!p){toast("Save the project first");return}const n=prompt("Name? 📄","notes.txt");if(!n)return;p.files=p.files||[];p.files.push({name:n.slice(0,64),type:"text",text:"Edit me..."});saveProjects(getProjects().map(x=>x.id===p.id?p:x));renderDash()}
function editText(i,v){const all=getProjects();const p=all.find(x=>x.id===editingId);if(!p||!p.files[i])return;p.files[i].text=String(v).slice(0,20000);saveProjects(all)}
function delFile(i){const all=getProjects();const p=all.find(x=>x.id===editingId);if(!p||!p.files[i])return;p.files.splice(i,1);saveProjects(all.map(x=>x.id===p.id?p:x));renderDash()}
function handleFiles(el){const p=getProjects().find(x=>x.id===editingId);if(!p){toast("Save the project first");return}Array.from(el.files||[]).forEach(f=>{const r=new FileReader();r.onload=()=>{const all=getProjects();const t=all.find(x=>x.id===editingId);if(!t)return;t.files=t.files||[];t.files.push({name:f.name.slice(0,64),type:f.type.startsWith("image/")?"image":"file",data:r.result});saveProjects(all);renderDash()};r.readAsDataURL(f)});el.value=""}
function saveAbout(){if(!isOwnerSession){toast("Unlock the studio first");return}const a=getAbout()||{};a.name=$("aNameIn").value.trim().slice(0,40)||"Darkz";a.tag=$("aTagIn").value.slice(0,120);a.bio=$("aBioIn").value.slice(0,2000);a.timeline=$("aTimeIn").value.split("\n").map(s=>s.trim()).filter(s=>s.length>0).slice(0,50);a.songTitle=$("aSongIn").value.slice(0,120);a.songUrl=$("aSongUrlIn").value.trim().slice(0,500)||a.songUrl||"";if(a.songUrl){idbDel("profile-song")}saveAboutStore(a);renderAll();toast("Saved")}
function clearBio(){$("aBioIn").value="";saveAbout()}
function clearTimeline(){$("aTimeIn").value="";saveAbout()}
function exportJSON(){const b=new Blob([JSON.stringify({projects:getProjects(),about:getAbout()},null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="darkz-hub-backup.json";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),5000)}
function importJSON(el){const f=el.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const j=JSON.parse(r.result);if(j&&Array.isArray(j.projects))saveProjects(j.projects);if(j&&j.about)saveAboutStore(j.about);renderAll();syncDashInputs();renderDash()}catch{toast("That file isn't valid JSON")}};r.readAsText(f);el.value=""}
function initSmooth(){if(localStorage.getItem("darkzhub-smooth")==="0")document.body.classList.add("no-motion");else document.body.classList.remove("no-motion");$("smoothBtn").textContent="Motion: "+(localStorage.getItem("darkzhub-smooth")==="0"?"off":"on");$("particleBtn").textContent="Particles: "+(localStorage.getItem("darkzhub-particles")==="0"?"off":"on")}
function makeOrbTexture(){const c=document.createElement("canvas");c.width=c.height=128;const x=c.getContext("2d");const g=x.createRadialGradient(64,64,0,64,64,64);g.addColorStop(0,"rgba(255,255,255,1)");g.addColorStop(0.25,"rgba(255,255,255,.9)");g.addColorStop(0.55,"rgba(255,255,255,.25)");g.addColorStop(1,"rgba(255,255,255,0)");x.fillStyle=g;x.fillRect(0,0,128,128);const t=new THREE.CanvasTexture(c);return t}
function getBgConfig(bg){if(bg==="stars")return {n:1600,size:.14,op:.95,sp:.0004,col1:[1,1,1],col2:[.6,.7,1]};if(bg==="emberbg")return {n:700,size:.32,op:.8,sp:.0015,col1:[1,.45,.15],col2:[1,.8,.4]};if(bg==="nebula")return {n:800,size:.5,op:.7,sp:.0008,col1:[.6,.3,1],col2:[0,.8,1]};if(bg==="aurora")return {n:900,size:.4,op:.6,sp:.0009,col1:[0,.9,1],col2:[.5,1,.7]};if(bg==="grid")return {n:350,size:.22,op:.5,sp:.0006,col1:[.7,.7,.8],col2:[.5,.5,.6]};return {n:1000,size:.34,op:.75,sp:.0011,col1:[1,1,1],col2:[1,.35,.35]}}
function initThree(){try{stopThree();if(localStorage.getItem("darkzhub-particles")==="0")return;if(!window.THREE)return;const bg=getBg();if(bg==="off")return;const canvas=$("bg3d");const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x050507,.028);const cam=new THREE.PerspectiveCamera(70,innerWidth/innerHeight,.1,100);cam.position.z=18;const ren=new THREE.WebGLRenderer({canvas,alpha:true,antialias:true});ren.setSize(innerWidth,innerHeight);threeRen=ren;const cfg=getBgConfig(bg);const g=new THREE.BufferGeometry();const pos=new Float32Array(cfg.n*3);const col=new Float32Array(cfg.n*3);for(let i=0;i<cfg.n;i++){pos[i*3]=(Math.random()-.5)*60;pos[i*3+1]=(Math.random()-.5)*40;pos[i*3+2]=(Math.random()-.5)*30;const mix=Math.random();col[i*3]=cfg.col1[0]*mix+cfg.col2[0]*(1-mix);col[i*3+1]=cfg.col1[1]*mix+cfg.col2[1]*(1-mix);col[i*3+2]=cfg.col1[2]*mix+cfg.col2[2]*(1-mix)}g.setAttribute("position",new THREE.BufferAttribute(pos,3));g.setAttribute("color",new THREE.BufferAttribute(col,3));const tex=makeOrbTexture();const mat=new THREE.PointsMaterial({size:cfg.size,map:tex,transparent:true,opacity:cfg.op,vertexColors:true,depthWrite:false,blending:THREE.AdditiveBlending,sizeAttenuation:true});threePts=new THREE.Points(g,mat);scene.add(threePts);(function anim(){threeAnim=requestAnimationFrame(anim);if(document.body.classList.contains("no-motion")){ren.render(scene,cam);return}cx+=(mx-cx)*.04;cy+=(my-cy)*.04;threePts.rotation.y+=cfg.sp;threePts.rotation.x+=cfg.sp*.35;threePts.position.x=cx*.8;threePts.position.y=-cy*.6;cam.position.x+=(cx*2.2-cam.position.x)*.04;cam.position.y+=(-cy*1.6-cam.position.y)*.04;cam.lookAt(scene.position);ren.render(scene,cam)})();addEventListener("resize",()=>{cam.aspect=innerWidth/innerHeight;cam.updateProjectionMatrix();ren.setSize(innerWidth,innerHeight)})}catch{}}
function initMouse(){document.addEventListener("mousemove",e=>{mx=(e.clientX/innerWidth-.5)*2;my=(e.clientY/innerHeight-.5)*2;gx=e.clientX;gy=e.clientY;lastAct=Date.now()});/* cursor glow retired with the v2 backdrop */}
function tilt(){/* retired in v2 — profile card is static */}
document.addEventListener("mousemove",()=>{lastAct=Date.now()});setInterval(()=>{if(isOwnerSession&&Date.now()-lastAct>20*60*1000){lockDash()}},60000);
document.body.dataset.theme=getTheme();document.body.dataset.bg=getBg();initSmooth();if(checkSession())isOwnerSession=true;renderAll();syncDashInputs();renderLock();tilt();initMouse();initThree();setTheme(getTheme());setBg(getBg());
